enum TypeKeys {
  ADD_TODO = 'ADD_TODO',
  REMOVE_TODO = 'REMOVE_TODO',
  EDIT_TODO = 'EDIT_TODO',
  SET_TODO_PROPS = 'SET_TODO_PROPS',
  SET_TODO_META_DATA = 'SET_TODO_META_DATA',
  SET_SEARCH_KEYWORDS = 'SET_SEARCH_KEYWORDS',
  SET_SEARCH_TAGS = 'SET_SEARCH_TAGS',
  SET_TODO_TO_EDIT = 'SET_TODO_TO_EDIT',
  SET_TAGS = 'SET_TAGS',
  TOGGLE_POPUP = 'TOGGLE_POPUP',
  SET_POPUP_EDIT_TITLE = 'SET_POPUP_EDIT_TITLE',
  TOGGLE_ADD_FORM = 'TOGGLE_ADD_FORM',
  SET_TITLE_TO_ADD = 'SET_TITLE_TO_ADD',
  SET_EXP_DATE_TO_ADD = 'SET_EXP_DATE_TO_ADD',
  SET_TAG_IDS_TO_ADD = 'SET_TAG_IDS_TO_ADD',
  SET_TAG_NAMES_TO_ADD = 'SET_TAG_NAMES_TO_ADD',
  RESET_TODO_TO_ADD = 'RESET_TODO_TO_ADD',
  RECEIVE_TOKENS_AND_USERDETAILS = 'RECEIVE_TOKENS_AND_USERDETAILS',
  REMOVE_TOKENS_AND_USERDETAILS = 'REMOVE_TOKENS_AND_USERDETAILS',
  SET_AUTHENTICATION = 'SET_AUTHENTICATION',
  SET_LOGIN_EMAIL = 'SET_LOGIN_EMAIL',
  SET_LOGIN_PASSWORD = 'SET_LOGIN_PASSWORD',
  RESET_STORE = 'RESET_STORE'
}

export default TypeKeys;